server:
  port: 8083

spring:
  application:
    name: file-service

file:
  storage:
    path: /app/uploads

eureka:
  client:
    service-url:
      defaultZone: http://node-a.platform:8761/eureka/, http://node-b.platform:8761/eureka/, http://node-c.platform:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
