server:
  port: 8082

spring:
  application:
    name: submission-service
  data:
    mongodb:
      uri: mongodb://services-vm-external-ip:27017/edusubmit_submission_db  # Update with actual IP

eureka:
  client:
    service-url:
      defaultZone: http://node-a.platform:8761/eureka/, http://node-b.platform:8761/eureka/, http://node-c.platform:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
